### PR TITLE
clk_div: Fix that counter was never reset

### PR DESCRIPTION
**Pull request by zarubaf**

### CODE REVIEW

**Review by andreaskurth — APPROVED** [review]
The bugfix looks good to me, but there are two other things in this module that do not make sense to me:

1. When dividing by an integer factor `RATIO`, why does the counter need `RATIO` bits instead of `$clog2(RATIO)` bits?
2. Is it on purpose that the output clock has a duty cycle < 50% (in fact, just one cycle of the input clock)?

**Comment by Xavier2979** [comment]
> The bugfix looks good to me, but there are two other things in this module that do not make sense to me:
> 
> 1. When dividing by an integer factor `RATIO`, why does the counter need `RATIO` bits instead of `$clog2(RATIO)` bits?
> 2. Is it on purpose that the output clock has a duty cycle < 50% (in fact, just one cycle of the input clock)?

**Comment by niwis** [comment]
This is a pretty old PR, but it looks to me like this issue still persists. I also agree with the observations of @accuminium regarding the counter width and duty cycle. Do you think we should proceed on this? In that case I could propose a fix on top of this PR.

**Comment by accuminium** [comment]
> Do you think we should proceed on this? In that case I could propose a fix on top of this PR.

That would be great! :+1:

**Comment by niwis** [comment]
Superseded by https://github.com/pulp-platform/common_cells/pull/132

**Pull request closed without merging**
