### PR TITLE
Add barrel shifter module

### PR DESCRIPTION
**Pull request by WRoenninger**
This adds a logarithmic barrel shifter.
* Can have different byte_width.
* Left or right parametrisation.

### CODE REVIEW

**Comment by zarubaf** [comment]
I let Steve weigh in. I am not entirely convinced that this performers better than the Synthesiser's `<<` implementation. Do you have any numbers?

**Comment by WRoenninger** [comment]
There where some numbers done by @thommythomaso. It seems that the design-ware implementation performs better.

**Comment by stmach** [comment]
Unless there is a tangible case where this is required and better over `result = {input, input} >> shift` or similar, I don't really see the necessity for a dedicated shifter module.
Realistically, any synthesizer will have a more or less target-optimized version of a shifter inferred from `>>`, which is also most portable.

**Comment by zarubaf** [comment]
So I am closing this PR for now. In case there is a necessity for merging or other opinions feel free to re-open or create another PR.

**Pull request closed without merging**
